name: Create Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build Web App
        run: npm run build
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r lightroom-photo-gallery.zip build
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.run_id }}
          generate_release_notes: true
          body: ${{ github.event.head_commit.message }}
          tag_name: latest
          files: lightroom-photo-gallery-${{ github.run_id }}.zip